// Protobuffer defs for sketch

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: sketch.proto

package sketchpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumRandomNumbers uint64 `protobuf:"varint,1,opt,name=num_random_numbers,json=numRandomNumbers,proto3" json:"num_random_numbers,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetNumRandomNumbers() uint64 {
	if x != nil {
		return x.NumRandomNumbers
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RandomNumber uint64 `protobuf:"varint,1,opt,name=random_number,json=randomNumber,proto3" json:"random_number,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sketch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRandomNumber() uint64 {
	if x != nil {
		return x.RandomNumber
	}
	return 0
}

var File_sketch_proto protoreflect.FileDescriptor

var file_sketch_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x70, 0x62, 0x22, 0x37, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x10, 0x6e, 0x75, 0x6d, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x22, 0x2f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x32, 0x47, 0x0a, 0x06, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x12, 0x3d, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x12, 0x11, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x3b, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_sketch_proto_rawDescOnce sync.Once
	file_sketch_proto_rawDescData = file_sketch_proto_rawDesc
)

func file_sketch_proto_rawDescGZIP() []byte {
	file_sketch_proto_rawDescOnce.Do(func() {
		file_sketch_proto_rawDescData = protoimpl.X.CompressGZIP(file_sketch_proto_rawDescData)
	})
	return file_sketch_proto_rawDescData
}

var file_sketch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sketch_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: sketchpb.Request
	(*Response)(nil), // 1: sketchpb.Response
}
var file_sketch_proto_depIdxs = []int32{
	0, // 0: sketchpb.Sketch.GetRandomNumbers:input_type -> sketchpb.Request
	1, // 1: sketchpb.Sketch.GetRandomNumbers:output_type -> sketchpb.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sketch_proto_init() }
func file_sketch_proto_init() {
	if File_sketch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sketch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sketch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sketch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sketch_proto_goTypes,
		DependencyIndexes: file_sketch_proto_depIdxs,
		MessageInfos:      file_sketch_proto_msgTypes,
	}.Build()
	File_sketch_proto = out.File
	file_sketch_proto_rawDesc = nil
	file_sketch_proto_goTypes = nil
	file_sketch_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SketchClient is the client API for Sketch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SketchClient interface {
	GetRandomNumbers(ctx context.Context, in *Request, opts ...grpc.CallOption) (Sketch_GetRandomNumbersClient, error)
}

type sketchClient struct {
	cc grpc.ClientConnInterface
}

func NewSketchClient(cc grpc.ClientConnInterface) SketchClient {
	return &sketchClient{cc}
}

func (c *sketchClient) GetRandomNumbers(ctx context.Context, in *Request, opts ...grpc.CallOption) (Sketch_GetRandomNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sketch_serviceDesc.Streams[0], "/sketchpb.Sketch/GetRandomNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &sketchGetRandomNumbersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Sketch_GetRandomNumbersClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type sketchGetRandomNumbersClient struct {
	grpc.ClientStream
}

func (x *sketchGetRandomNumbersClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SketchServer is the server API for Sketch service.
type SketchServer interface {
	GetRandomNumbers(*Request, Sketch_GetRandomNumbersServer) error
}

// UnimplementedSketchServer can be embedded to have forward compatible implementations.
type UnimplementedSketchServer struct {
}

func (*UnimplementedSketchServer) GetRandomNumbers(*Request, Sketch_GetRandomNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRandomNumbers not implemented")
}

func RegisterSketchServer(s *grpc.Server, srv SketchServer) {
	s.RegisterService(&_Sketch_serviceDesc, srv)
}

func _Sketch_GetRandomNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SketchServer).GetRandomNumbers(m, &sketchGetRandomNumbersServer{stream})
}

type Sketch_GetRandomNumbersServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type sketchGetRandomNumbersServer struct {
	grpc.ServerStream
}

func (x *sketchGetRandomNumbersServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _Sketch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sketchpb.Sketch",
	HandlerType: (*SketchServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRandomNumbers",
			Handler:       _Sketch_GetRandomNumbers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sketch.proto",
}
